package src;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author npquy
 */
public class HotelResult extends javax.swing.JPanel {

    /** Creates new form TourResult */
    public HotelResult() {
        initComponents();
        //setBackground(new java.awt.Color(0,0,0,0));
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        hotelName = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        see_more_label = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_images/hotel_holt.png"))); // NOI18N
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 140));

        address.setFont(new java.awt.Font("Malayalam MN", 0, 11)); // NOI18N
        address.setText("Aðalstræti 13");
        add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 45, 140, 10));

        hotelName.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        hotelName.setText("Hotel Holt");
        add(hotelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 150, -1));

        rating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_images/5_stars.png"))); // NOI18N
        add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 90, -1));

        see_more_label.setBackground(new java.awt.Color(204, 204, 204));
        see_more_label.setText("See more");
        see_more_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        see_more_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        see_more_label.setOpaque(true);
        see_more_label.setHorizontalAlignment(JLabel.CENTER);
        add(see_more_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, -1));

        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.setForeground(new java.awt.Color(153, 51, 0));
        price.setText("ISK 2000");
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 86, 150, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel hotelName;
    private javax.swing.JLabel image;
    private javax.swing.JLabel price;
    private javax.swing.JLabel rating;
    private javax.swing.JLabel see_more_label;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getAddress() {
        return address;
    }

    public javax.swing.JLabel getHotelName() {
        return hotelName;
    }

    public javax.swing.JLabel getImage() {
        return image;
    }

    public javax.swing.JLabel getRating() {
        return rating;
    }
    
    public javax.swing.JLabel getPrice() {
        return price;
    }

    public javax.swing.JLabel getSee_more_label() {
        return see_more_label;
    }

}
